name: CI Pipeline

on: push
jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        run: |
          sudo apt-get install -y libusb-1.0-0-dev
          sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
          pip install opencv-python numpy
          export LIBUSB_1_INCLUDE_DIR=/usr/include/libusb-1.0/
          mkdir build
          cd build
          cmake -L .. -DBUILD_PYTHON3=ON
          make
          rm -r src
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.run_id }}
          overwrite: true
          path: build
