name: CI Pipeline

on: push
jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        run: |
          sudo apt-get install -y libusb-1.0-0-dev
          export LIBUSB_1_INCLUDE_DIR=/usr/include/libusb-1.0/
          mkdir build
          cd build
          cmake -L ..
          make
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          path: build
